### ISSUE TITLE
inconsistent formatting when using numberfield

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-text-field-flow#172]
```
		NumberField nf = new NumberField();
		nf.setValue(10d);
		add(nf);

		nf.setStep(1);

		Button button = new Button("Click me", event -> nf.setValue(nf.getValue() + 1));
		add(button);
	}
```

the value starts out with '10' and changes to '11.0'. it hsould be consistent, probably '10.0' from the beginning.

**Comment by martinisraelsen** [comment]
I have experienced the same issue, but opposite. It starts with a 1.0 and then removes the .0 after clicking the step button. I agree it should be consistent, but would argue that decimals should only be shown if the value has decimals or the step value allows for decimals (e.g. step .1)

**Comment by robert-lee-hisl** [comment]
My use case is editing whole numbers and currency values, ie exactl numbers of decimal places. This could either be worked out based on the value/step, or set explicitly, but it needs to be consistent.

**Comment by yuriy-fix** [comment]
The fixes and updates of the `number-field` behaviour that was applied in `vaadin-text-field` [2.4.0](https://github.com/vaadin/vaadin-text-field/releases/tag/v2.4.0) should fix the issue. 
This version was not included in Vaadin 13, but will be available in Vaadin 14.
If you would like to use right away, please use the webjar dependency:
```
<dependency>
  <groupId>org.webjars.bowergithub.vaadin</groupId>
  <artifactId>vaadin-text-field</artifactId>
  <version>2.4.0</version>
</dependency>
```

**Comment by yuriy-fix** [comment]
Update to the ticket: The initial value on Flow side is set incorrectly with adjusting the value to have strictly 1 decimal place. After adjusting with controls the value has correct number of decimal places.
Example (initial values: `1`, `1.0`, `1.10` / steps: `1`, `0.1`, `0.01`):
![number-field](https://user-images.githubusercontent.com/29372419/57846751-8f781480-77dd-11e9-8958-13d98717b293.gif)

**Comment by Legioth** [comment]
> The initial value on Flow side is set incorrectly

Shouldn't the web component take care of showing the value in a consistent way regardless of how the value been set?

**Comment by TatuLund** [comment]
So am I right if it is this vaadin-text-field web component issue that should be fixed then, and  https://github.com/vaadin/vaadin-text-field/issues/361 ?

**Comment by pleku** [comment]
Based on user report, this has been fixed in 14 prerelease but not closed for some reason.

**Comment by ManuelAtJEE** [comment]
@pleku  Based on our experiences with Vaadin 14, this bug still not fixed.
Please have a look on your own example:
The initial value is "1.0". After incrementing with "+" the value is "2", as expected.
https://vaadin.com/components/vaadin-text-field/java-examples/number-field

(please consider, that we are paying customers)

**Comment by pleku** [comment]
@ManuelAtJEE it should have been fixed with the web component version v2.4.9 which is included in `14.0.2` and is in use in vaadin.com examples, but it seems that for the case you're referring to it doesn't still work the way you expect it to work ? I've reopened this issue, you may use warranty to prioritize the fix.

There is also another example `Number field with step` which has a `0.2` step and it also loses the decimal. The same happens for the HTML Examples. Ping @tomivirkki

**Comment by kolle1986** [comment]
Problem still exists in vaadin 14.0.5 on java side created number field. I want to see only integers but can't manage to set initial value without decimals
