### ISSUE TITLE
Empty non-required EmailField is invalid (also initially, before the first visit)

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-text-field-flow#236]
Steps to reproduce:
1. `add(new EmailField());`
2. Notice that the empty non-visited field is invalid

It's because empty string doesn't match the email-pattern. Empty string should not be invalidated as invalid email address, as we have `setRequired` for that purpose.

Also, a field should not be invalidated before the user has even visited it.

**Comment by tomivirkki** [comment]
Fixed in the latest release

**Comment by stefanuebe** [comment]
Still occurs. When writing a valid email address to an EmailField and removing it, the field becomes invalid.

Steps to reproduce:
1. `add(new EmailField())`
2. Open the application (the email field is not marked as invalid on startup). 
3. Write some valid email into the field. Blur the field.
4. Remove the value. Blur the field. The field will be marked as invalid.

Reproducible with latest LTS Spring Boot starter (14.1.25)
